
export const russianContent = {
  common: {
    create: "Создать",
    edit: "Редактировать",
    delete: "Удалить",
    cancel: "Отмена",
    save: "Сохранить",
    confirm: "Подтвердить",
    back: "Назад",
    close: "Закрыть",
    search: "Поиск",
    filter: "Фильтр",
    all: "Все",
    active: "Активные",
    completed: "Завершенные",
    draft: "Черновик",
    status: "Статус",
    actions: "Действия",
    view: "Просмотр",
    manage: "Управление",
    assign: "Назначить",
    remove: "Удалить",
    contact: "Связаться",
    sendMessage: "Отправить сообщение",
    volunteers: "Волонтеры",
    donations: "Пожертвования",
    events: "Мероприятия",
    profile: "Профиль",
    myEvents: "Мои мероприятия",
    myDonations: "Мои пожертвования",
    profileInfo: "Информация профиля",
    dashboard: "Панель управления",
  },
  statusTranslations: {
    draft: "Черновик",
    active: "Активно",
    completed: "Завершено",
    cancelled: "Отменено"
  },
  events: {
    createEvent: "Создать мероприятие",
    eventTitle: "Название мероприятия",
    description: "Описание",
    date: "Дата",
    time: "Время",
    location: "Место проведения",
    category: "Категория",
    volunteersNeeded: "Требуется волонтеров",
    fundraisingGoal: "Цель сбора средств",
    publishEvent: "Опубликовать мероприятие",
    saveAsDraft: "Сохранить как черновик",
    joinAsVolunteer: "Стать волонтером",
    donate: "Сделать пожертвование",
    share: "Поделиться",
    manageVolunteers: "Управление волонтерами",
    viewDonations: "Просмотр пожертвований",
    totalEvents: "Всего мероприятий",
    totalVolunteers: "Всего волонтеров",
    totalDonations: "Всего пожертвований",
    impactScore: "Помощь оказана",
    noEventsFound: "Мероприятия не найдены",
    adjustFilters: "Попробуйте изменить фильтры, чтобы увидеть больше результатов.",
    noEventsCreated: "Вы еще не создали мероприятий.",
    clearFilters: "Очистить фильтры",
    photo: "Фото",
  },
  categories: {
    animals: "Животные",
    environment: "Окружающая среда",
    health: "Здоровье",
    education: "Образование",
    poverty: "Нуждающиеся",
    community: "Сообщество"
  },
  volunteers: {
    name: "Имя",
    email: "Электронная почта",
    phone: "Телефон",
    event: "Мероприятие",
    joinDate: "Дата присоединения",
    assignTask: "Назначить задачу",
    taskTitle: "Название задачи",
    taskDescription: "Описание задачи",
    taskDueDate: "Срок выполнения",
  },
  donations: {
    donor: "Жертвователь",
    amount: "Сумма",
    date: "Дата",
    event: "Мероприятие",
    sendThankYou: "Отправить благодарность",
    recordInfo: "Записать информацию",
    viewDetails: "Посмотреть детали",
  },
  profile: {
    firstName: "Имя",
    lastName: "Фамилия",
    email: "Электронная почта",
    phone: "Телефон",
    address: "Адрес",
    city: "Город",
    country: "Страна",
    postalCode: "Почтовый индекс",
    updateProfile: "Обновить профиль",
    changePassword: "Изменить пароль",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердите пароль",
  },
  chat: {
    newMessage: "Новое сообщение",
    sendMessage: "Отправить сообщение",
    typeMessage: "Введите сообщение...",
    noMessages: "Нет сообщений",
    startConversation: "Начните разговор прямо сейчас!",
  },
  modals: {
    deleteConfirmation: "Подтверждение удаления",
    deleteWarning: "Вы уверены, что хотите удалить это? Это действие нельзя отменить.",
    deleteEvent: "Удалить мероприятие",
    deleteVolunteer: "Удалить волонтера",
    deleteDonation: "Удалить пожертвование",
  }
};
